name: Setup New Project From Template

on:
  workflow_dispatch:
    inputs:
      new_project_name:
        description: 'New Project Name'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Run renaming script
      run: ruby rename_rails_app.rb ${{ github.event.inputs.new_project_name }}
      env:
        RAILS_ENV: development

    - name: Configure git with GitHub Actions user
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Renamed Rails application to ${{ github.event.inputs.new_project_name }}" || echo "No changes to commit"
        git push --set-upstream origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
